# Generated by Django 5.1.4 on 2024-12-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_productimage'),
        ('user', '0008_deliveryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user.seller'),
            preserve_default=False,
        ),
    ]
