# Generated by Django 5.1.4 on 2024-12-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_quantity_product_seller_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
