# Generated by Django 5.1.4 on 2024-12-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_productimage'),
        ('user', '0002_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'product')},
        ),
    ]
