# Generated by Django 5.1.4 on 2024-12-16 10:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_first_name_remove_user_last_name_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', unique=True)),
                ('passport_number', models.CharField(max_length=300, unique=True)),
                ('jshshir', models.CharField(max_length=50, unique=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
