# Generated by Django 5.1.4 on 2024-12-16 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='user.region')),
            ],
        ),
    ]
