# Generated by Django 5.1.4 on 2024-12-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_deliveryprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In process', 'In process'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='In progress', max_length=100),
        ),
    ]
