# Generated by Django 5.1.4 on 2024-12-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_thread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='name',
            new_name='title',
        ),
    ]
