# Generated by Django 5.1.4 on 2024-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_name_thread_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcart',
            name='thread_discount',
            field=models.IntegerField(default=0),
        ),
    ]
