# Generated by Django 5.1.4 on 2024-12-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_aboutcart_thread_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutorder',
            name='thread_discount',
            field=models.IntegerField(default=0),
        ),
    ]
