# Generated by Django 5.1.4 on 2024-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_aboutcart_thread_user_aboutorder_thread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutorder',
            name='thread_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Canceled', 'Canceled'), ('Paid', 'Paid')], default='Waiting', max_length=100),
        ),
    ]
