# Generated by Django 5.1.4 on 2024-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_aboutorder_thread_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
