# Generated by Django 5.1.4 on 2024-12-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_thread_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread_discount',
        ),
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread_user',
        ),
        migrations.AddField(
            model_name='aboutorder',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_order', to='user.thread'),
        ),
    ]
