# Generated by Django 5.1.4 on 2024-12-18 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_aboutorder_thread_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutorder',
            name='thread',
        ),
        migrations.AddField(
            model_name='aboutcart',
            name='thread_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aboutorder',
            name='thread_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aboutorder',
            name='thread_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aboutorder',
            name='thread_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aboutorder',
            name='thread_status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Canceled', 'Canceled'), ('Paid', 'Paid')], max_length=100, null=True),
        ),
    ]
