# Generated by Django 5.1.4 on 2024-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_aboutorder_thread_aboutcart_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='canceled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='delivering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
