# Generated by Django 5.1.4 on 2024-12-18 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_thread_canceled_thread_delivering_thread_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='visited',
        ),
        migrations.CreateModel(
            name='VisitedIpAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IPs', to='user.thread')),
            ],
        ),
    ]
