# Generated by Django 5.1.4 on 2024-12-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_blockedip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='delivering',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='sold',
        ),
    ]
