# Generated by Django 5.1.4 on 2024-12-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_owner'),
        ('user', '0025_thread_canceled_thread_delivering_thread_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='konkurs/')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
