# Generated by Django 5.1.4 on 2024-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_competition_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(default=0),
        ),
    ]
