# Generated by Django 5.1.4 on 2024-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('Paid', 'Paid'), ('canceled', 'Canceled')], default='waiting', max_length=50),
        ),
    ]
