# Generated by Django 5.1.4 on 2024-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_withdraw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='waiting', max_length=50),
        ),
    ]
