# Generated by Django 5.1.4 on 2024-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
