# Generated by Django 5.1.4 on 2024-12-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In process', 'in process'), ('Canceled', 'canceled'), ('Delivered', 'delivered'), ('Delivering', 'delivering')], default='In process', max_length=100),
        ),
    ]
