# Generated by Django 5.1.4 on 2024-12-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In process', 'in process'), ('Canceled', 'canceled'), ('Delivered', 'delivered'), ('Delivering', 'delivering')], default='in process', max_length=100),
        ),
    ]
